export const codeErrors = [
    { code: '400', title: 'Bad Request', desc: 'Sorry, the server could not understand the request.' },
    { code: '401', title: 'Unauthorized', desc: 'Sorry, you are not authorized to access this page.' },
    { code: '402', title: 'Payment Required', desc: 'Sorry, payment is required to access this page.' },
    { code: '403', title: 'Forbidden', desc: 'Sorry, you are forbidden from accessing this page.' },
    { code: '404', title: 'Page Not Found', desc: 'Sorry, the page you are looking for could not be found.' },
    { code: '405', title: 'Method Not Allowed', desc: 'Sorry, the request method is not allowed for this resource.' },
    { code: '406', title: 'Not Acceptable', desc: 'Sorry, the server cannot generate a response acceptable to the client.' },
    { code: '408', title: 'Request Timeout', desc: 'Sorry, the server timed out waiting for the request.' },
    { code: '409', title: 'Conflict', desc: 'Sorry, the request could not be completed due to a conflict with the current state of the resource.' },
    { code: '410', title: 'Gone', desc: 'Sorry, the resource you are looking for is no longer available.' },
    { code: '411', title: 'Length Required', desc: 'Sorry, a valid Content-Length header is required.' },
    { code: '412', title: 'Precondition Failed', desc: 'Sorry, the server does not meet one of the preconditions specified in the request.' },
    { code: '413', title: 'Payload Too Large', desc: 'Sorry, the request payload is too large.' },
    { code: '414', title: 'URI Too Long', desc: 'Sorry, the requested URI is too long to be processed.' },
    { code: '415', title: 'Unsupported Media Type', desc: 'Sorry, the media type of the requested data is not supported by the server.' },
    { code: '416', title: 'Range Not Satisfiable', desc: 'Sorry, the server cannot provide the requested range.' },
    { code: '417', title: 'Expectation Failed', desc: 'Sorry, the server could not meet the expectations given in the request header.' },
    { code: '418', title: 'I\'m a teapot', desc: 'Sorry, I\'m a teapot.' },
    { code: '419', title: 'Page Expired', desc: 'Sorry, your session has expired. Please refresh and try again.' },
    { code: '421', title: 'Misdirected Request', desc: 'Sorry, the request was directed at a server that is not able to produce a response.' },
    { code: '422', title: 'Unprocessable Entity', desc: 'Sorry, the server understands the content type of the request entity, but was unable to process the contained instructions.' },
    { code: '423', title: 'Locked', desc: 'Sorry, the resource that is being accessed is locked.' },
    { code: '424', title: 'Failed Dependency', desc: 'Sorry, the request failed due to failure of a previous request.' },
    { code: '426', title: 'Upgrade Required', desc: 'Sorry, the client should switch to a different protocol.' },
    { code: '428', title: 'Precondition Required', desc: 'Sorry, the server requires the request to be conditional.' },
    { code: '429', title: 'Too Many Requests', desc: 'Sorry, you have sent too many requests in a given amount of time.' },
    { code: '431', title: 'Request Header Fields Too Large', desc: 'Sorry, the server is unwilling to process the request because its header fields are too large.' },
    { code: '451', title: 'Unavailable For Legal Reasons', desc: 'Sorry, the server is denying access to the resource as a consequence of a legal demand.' },
    { code: '500', title: 'Server Error', desc: 'Whoops, something went wrong on our servers.' },
    { code: '501', title: 'Not Implemented', desc: 'Sorry, the server does not recognize the request method or lacks the ability to fulfill it.' },
    { code: '502', title: 'Bad Gateway', desc: 'Sorry, the server received an invalid response from an inbound server.' },
    { code: '503', title: 'Service Unavailable', desc: 'Sorry, we are doing some maintenance. Please check back soon.' },
    { code: '504', title: 'Gateway Timeout', desc: 'Sorry, the server did not receive a timely response from an upstream server.' },
    { code: '505', title: 'HTTP Version Not Supported', desc: 'Sorry, the server does not support the HTTP protocol version used in the request.' },
    { code: '507', title: 'Insufficient Storage', desc: 'Sorry, the server is unable to store the representation needed to complete the request.' },
    { code: '508', title: 'Loop Detected', desc: 'Sorry, the server detected an infinite loop while processing the request.' },
    { code: '510', title: 'Not Extended', desc: 'Sorry, further extensions to the request are required for the server to fulfill it.' },
    { code: '511', title: 'Network Authentication Required', desc: 'Sorry, the client needs to authenticate to gain network access.' },
  ];